<a href="https://colab.research.google.com/github/PalmerTurley34/DS-Unit-4-Sprint-2-Neural-Networks/blob/main/LS_DS_432_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Using TensorFlow Keras, Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn.

This is your "Hello World!" of TensorFlow.

### Example TensorFlow Starter Code

```python 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

results = model.fit(X,y, epochs=100)

```

### Additional Written Tasks:
1. Investigate the various [loss functions](https://www.tensorflow.org/api_docs/python/tf/keras/losses). Which is best suited for the task at hand (predicting 1 / 0) and why? 
2. What is the difference between a loss function and a metric? Why might we need both in Keras? 
3. Investigate the various [optimizers](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers). Stochastic Gradient Descent (`sgd`) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as `adam` have to offer? 

1. Since the target is binary, binary_crossentropy would be best suited for the loss function.

2. A loss function is a function that the model tries to minimize. A metric has nothing to do with the model, it's what we are able to look at to see how the model is performing.

3. Adam seems to be like sgd but is more complex, the goal seems to be to update the weights enough but not too much, which can be a problem for sgd.

### Build a Tensor Keras Perceptron

Try to match the architecture we used on Monday - inputs nodes and one output node. Apply this architecture to the XOR-ish dataset above. 

After fitting your model answer these questions: 

Are you able to achieve the same results as a bigger architecture from the first part of the assignment? Why is this disparity the case? What properties of the XOR dataset would cause this disparity? 

Now extrapolate this behavior on a much larger dataset in terms of features. What kind of architecture decisions could we make to avoid the problems the XOR dataset presents at scale? 

*Note:* The bias term is baked in by default in the Dense layer.

In [5]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam, SGD

In [10]:
model = Sequential([
                    Dense(3, activation='sigmoid', input_dim=3),
                    Dense(1, activation='sigmoid')
])

sgd = SGD()
adam = Adam()

In [11]:
model.compile(optimizer=sgd, loss='binary_crossentropy', metrics=['acc'])

In [3]:
import pandas as pd

df = pd.DataFrame({'x1': [0,0,1,0,1,1,0], 'x2': [0,1,0,1,0,1,0], 'x3': [1,1,1,0,0,1,0], 'y': [0,1,1,1,1,0,0]})
df

x1  x2  x3  y
0   0   0   1  0
1   0   1   1  1
2   1   0   1  1
3   0   1   0  1
4   1   0   0  1
5   1   1   1  0
6   0   0   0  0

In [8]:
X = df[['x1', 'x2', 'x3']]
y = df['y']

In [12]:
model.fit(X,y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9529 - acc: 0.4286
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9506 - acc: 0.4286
Epoch 3/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9483 - acc: 0.4286
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 0.9461 - acc: 0.4286
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.9439 - acc: 0.4286
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9417 - acc: 0.4286
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9395 - acc: 0.4286
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9373 - acc: 0.4286
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.9351 - acc: 0.4286
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.9330 - acc: 0.4286
Epoch 11/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9309 

## Try building/training a more complex MLP on a bigger dataset.

Use TensorFlow Keras & the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the canonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the Internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [13]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [17]:
# input image dimensions
img_rows, img_cols = 28, 28

In [14]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [15]:
x_train.shape

(60000, 28, 28)

In [18]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [19]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simplify the problem for now: Zero or all else.

In [ ]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [ ]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [54]:
##### Your Code Here #####
model = Sequential([
                    Dense(5, activation='sigmoid', input_dim=784),
                    Dense(5, activation='sigmoid'),
                    Dense(10, activation='softmax')
])

model.compile(optimizer=adam, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [55]:
model.fit(x_train, y_train, epochs=25)

Epoch 1/25
1875/1875 [==============================] - 3s 1ms/step - loss: 1.5321 - accuracy: 0.4937
Epoch 2/25
1875/1875 [==============================] - 3s 1ms/step - loss: 1.1170 - accuracy: 0.6433
Epoch 3/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.9069 - accuracy: 0.7518
Epoch 4/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.7410 - accuracy: 0.7961
Epoch 5/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6591 - accuracy: 0.8139
Epoch 6/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6150 - accuracy: 0.8234
Epoch 7/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.5856 - accuracy: 0.8300
Epoch 8/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.5608 - accuracy: 0.8355
Epoch 9/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.5371 - accuracy: 0.8423
Epoch 10/25
1875/1875 [==============================] - 3s 1ms/step - loss: 0.513

In [56]:
y_pred_proba = model.predict(x_test)

In [58]:
y_pred_proba[0]

array([4.49213900e-07, 1.38422735e-02, 1.36544928e-03, 3.73683660e-03,
       1.95936209e-05, 9.79847464e-05, 9.88620741e-07, 9.74976242e-01,
       1.13965390e-04, 5.84618468e-03], dtype=float32)

In [60]:
y_pred = [list(y_pred_proba[i]).index(max(y_pred_proba[i])) for i in range(len(y_pred_proba))]

In [61]:
y_pred[:10]

[7, 2, 1, 0, 4, 1, 4, 9, 0, 9]

In [62]:
y_test[:10]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9], dtype=uint8)

In [63]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8793

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?